name: release
on:
  push:
    tags: [ "v*.[0-99]" ] # only a valid semver tag

jobs:    
  goreleaser:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Unshallow clone
        run: git fetch --prune --unshallow
      - name: Install Go 1.21
        uses: actions/setup-go@v6
        with:
          go-version: '1.26.x'
      - name: Goreleaser publish
        uses: goreleaser/goreleaser-action@v7
        with:
          args: release --clean
          version: "~> v2"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HOMEBREW_TOKEN: ${{ secrets.HOMEBREW_TOKEN }}
